### ISSUE TITLE
[UI Bug] Frontend sends invalid notice parameter (qualityGateCaYCConditionsSimplification) to /api/users/dismiss_notice, causing 400 Bad Request

### ISSUE THREAD

**Issue by grummans614** [mc1arke/sonarqube-community-branch-plugin#1182]
Describe the bug
When dismissing certain onboarding or guidance notices (e.g., "Clean as You Code" banner) via UI buttons like "Not now", the frontend sends an invalid value for the notice parameter: qualityGateCaYCConditionsSimplification.

However, the API /api/users/dismiss_notice only accepts a predefined set of valid keys (as documented in [SonarQube Web API](https://next.sonarqube.com/sonarqube/web_api/api/users/dismiss_notice)). This results in a 400 Bad Request error with response:

``` json
{
  "errors": [
    {
      "msg": "Value of parameter 'notice' (qualityGateCaYCConditionsSimplification) must be one of: [educationPrinciples, sonarlintAd, showNewModesTour, showDesignAndArchitectureBanner, showNewModesBanner, issueCleanCodeGuide, issueNewIssueStatusAndTransitionGuide, showDesignAndArchitectureOptInBanner, overviewZeroNewIssuesSimplification, showDesignAndArchitectureTour, showEnableSca]"
    }
  ]
}
```
This is a frontend validation bug — the UI should only send values from the allowed list.

To Reproduce

- Go to SonarQube Dashboard → open any project.
- Click “Not now” on the “Clean as You Code” banner (or similar notice).
- Open browser DevTools → Network tab → find request to /api/users/dismiss_notice.
- See request payload contains: notice=qualityGateCaYCConditionsSimplification
- Observe response: 400 Bad Request with error message listing allowed values.

Expected behavior
The UI should send only valid notice keys as defined by the API. For example:

If dismissing CAYC-related notice → send issueCleanCodeGuide or overviewZeroNewIssuesSimplification
Never send custom/unlisted keys like qualityGateCaYCConditionsSimplification
The notice should be dismissed silently without error.

Software Versions
SonarQube Version: 25.10.0.114319
Plugin Version: 25.9.0

Additional context
The API documentation clearly lists acceptable values for notice:
👉 https://next.sonarqube.com/sonarqube/web_api/api/users/dismiss_notice
The key qualityGateCaYCConditionsSimplification appears to be internal or deprecated, and should not be exposed to the API.
This bug affects user experience and may cause confusion when users see errors after simple actions.
It’s likely that this key was used internally in older versions but was never added to the public allowed list.

**Comment by splitt3r** [comment]
This was already discussed in https://github.com/mc1arke/sonarqube-community-branch-plugin/issues/1165#issuecomment-3545199375 and should be fixed by https://github.com/mc1arke/sonarqube-community-branch-plugin/pull/1177.

**Comment by mc1arke** [comment]
This looks like Sonarsource [removed the enum value from the back-end](https://github.com/SonarSource/sonarqube/commit/9ecb5cd9c788d67848d69c7598860b7238cd1e37) in 25.10 but [only removed the front-end reference](https://github.com/SonarSource/sonarqube-webapp/commit/efe040e0a6564ba8a0c500d56ac83a43ff3c10b7) in 25.11, so this will only be fixed in 25.11 of the plugin.

Note: next.sonarqube.com is the nightly build of Sonarqube and is based on various snapshots so the API definition you see on there may not be representative of the API on a released version of Sonarqube

**Comment by mc1arke** [comment]
25.11 of the plugin has now been released which should align front-end and back-end functionality for the dismiss_notice endpoint

**Comment by dawidsoftiq** [comment]
I've upgraded to 26.3 and this issue is still here:
`Value of parameter 'notice' (showNewModesTour) must be one of: [educationPrinciples, sonarlintAd, showDesignAndArchitectureBanner, showNewModesBanner, showSandboxedIssuesIntro, issueCleanCodeGuide, issueNewIssueStatusAndTransitionGuide, showDesignAndArchitectureOptInBanner, overviewZeroNewIssuesSimplification, showDesignAndArchitectureTour, showEnableSca]`

**Comment by mc1arke** [comment]
I don't have a reference to`showNewModesTour` in my workspace - can you share a screenshot of the page you're getting an option to perform the action that causes this error?

**Comment by dawidsoftiq** [comment]
Here it is:

<img width="2852" height="2052" alt="Image" src="https://github.com/user-attachments/assets/aead95c5-f1fa-4393-91af-f8936d990252" />

**Comment by splitt3r** [comment]
> Hello, any news please ? 
> Same issue with 26.4, can you fix this ?
> 
> Thanks.
> 
> @mc1arke 

For me it is fixed in 26.4.
